### ISSUE TITLE
Squeezing peak performance out of the cloud CI

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_preprocessing#82]
I am pretty happy with the setup we have right now, but I am wondering if we can speed up the test setup even more. 

Currently each one of the tests runs for ~16 minutes [example](https://github.com/jbusecke/cmip6_preprocessing/runs/1794165405?check_suite_focus=true). This is split into ~4 minutes setup and ~12 minutes actual testing. 

I will think about how to reduce the testing time, but we might be limited by I/O there? (What would be a good and easy way to profile such a job?)

On the other hand I was wondering if there are ways to get even faster setup of the environments? The more jobs we run in parallel, the more beneficial it would be to reduce this to a minimum.

I remember @andersy005 had a custom docker image? that was cached? If anybody here has some ideas or suggestions how to speed up the setup [here](https://github.com/jbusecke/cmip6_preprocessing/blob/96d28115ebef8e068457e194c3ce665aafd6c5b5/.github/workflows/ci.yaml#L90-L128) even further I would very much appreciate it.

**Comment by andersy005** [comment]
@jbusecke, 

- I am seeing `pytest-xdist` listed in your conda environments, but I don't see it being used to run tests. Have you looked into it yet (e.g.: `pytest -n auto --maxfail 5 --reruns 1 ....`? 

- I'd recommend using conda-forge channel only and setting the channel priority to strict. Also, the current conda setup configures mamba but it doesn't use it to setup the environment: https://github.com/jbusecke/cmip6_preprocessing/blob/a5ae25867afe509095de8757b5c1ba92192e0549/.github/workflows/ci.yaml#L34-L39

I'd try these settings to see if there is any improvements:

```yaml
- uses: conda-incubator/setup-miniconda@v2
  with:
    channels: conda-forge
    mamba-version: '*'
    channel-priority: strict
    activate-environment: test_env_cmip6_preprocessing # Defined in ci/environment*.yml
    auto-update-conda: false
    python-version: ${{ matrix.python-version }}
    use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
- name: Set up conda environment
  shell: bash -l {0}
  run: |
    mamba env update -f ci/environment-py${{ matrix.python-version }}.yml
    python -m pip install -e . --no-deps --force-reinstall
    conda list
```
